version: "3.2"
services:
        cssow-db:
                build: ./docker/cssow-db
                image: drussell1974/cssow_cssow-db:1.0.6-mariadb10.5
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: "${CSSOW_DB__ROOT_PASSWORD}"
                        MYSQL_DATABASE: "${CSSOW_DB__DATABASE}"
                        MYSQL_USER: "${CSSOW_DB__USER}"
                        MYSQL_PASSWORD: "${CSSOW_DB__PASSWORD}"
                volumes:
                        - "db_data:${CSSOW_DB__DBSERVER_PATH}"
                        - "${CSSOW_DB__BUILD_SCRIPT_PATH_SOURCE}:${CSSOW_DB__BUILD_SCRIPT_PATH_DEST}"
        teacher-web:
                build: ./docker/teacher-web
                image: drussell1974/cssow_teacher-web:1.0.1-python3
                environment:
                        TEACHER_WEB__WEB_SERVER_IP: "${TEACHER_WEB__WEB_SERVER_IP}"
                        TEACHER_WEB__WEB_SERVER_PORT_EXT: "${TEACHER_WEB__WEB_SERVER_PORT_EXT}"
                        TEACHER_WEB__WEB_SERVER_PORT_INT: "${TEACHER_WEB__WEB_SERVER_PORT_INT}"
                        TEACHER_WEB__WEB_SERVER_HOST_EXT: "${TEACHER_WEB__WEB_SERVER_HOST_EXT}"
                        TEACHER_WEB__WEB_SERVER_HOST_INT: "${TEACHER_WEB__WEB_SERVER_HOST_INT}"
                        TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_EXT: "${TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_EXT}"
                        TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_INT: "${TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_INT}"
                        TEACHER_WEB__WEB_SERVER_SECRET_KEY: "${TEACHER_WEB__WEB_SERVER_SECRET_KEY}"
                        TEACHER_WEB__WEB_SERVER_DEBUG: "${TEACHER_WEB__WEB_SERVER_DEBUG}"
                        STUDENT_WEB__WEB_SERVER_WWW: "${STUDENT_WEB__WEB_SERVER_WWW}"
                        EMAIL_SERVER__HOST_EXT: "${EMAIL_SERVER__HOST_EXT}"
                        EMAIL_SERVER__PORT_EXT: "${EMAIL_SERVER__PORT_EXT}"
                        EMAIL_SERVER__HOST_USER: "${EMAIL_SERVER__HOST_USER}"
                        CSSOWMODEL_APP__VERSION: "${CSSOWMODEL_APP__VERSION}"
                        CSSOW_DB__HOST_INT: "${CSSOW_DB__HOST_INT}"
                        CSSOW_DB__PORT_INT: "${CSSOW_DB__PORT_INT}"
                        CSSOW_DB__DATABASE: "${CSSOW_DB__DATABASE}"
                        CSSOW_DB__USER: "${CSSOW_DB__USER}"                        
                        CSSOW_DB__PASSWORD: "${CSSOW_DB__PASSWORD}"
                links:
                        - "${CSSOW_DB__HOST_INT}:${CSSOW_DB__HOST_EXT}"
                ports:
                        - "${TEACHER_WEB__WEB_SERVER_PORT_INT}:${TEACHER_WEB__WEB_SERVER_PORT_EXT}"
                depends_on:
                        - cssow-db
        student-web:
                build: ./docker/student-web
                image: drussell1974/cssow_student-web:1.0-node14.3
                environment: 
                        STUDENT_WEB__WEB_SERVER_IP: "${STUDENT_WEB__WEB_SERVER_IP}"
                        STUDENT_WEB__WEB_SERVER_PORT_EXT: "${STUDENT_WEB__WEB_SERVER_PORT_EXT}"
                        STUDENT_WEB__WEB_SERVER_PORT_INT: "${STUDENT_WEB__WEB_SERVER_PORT_INT}"
                        STUDENT_WEB__WEB_SERVER_HOST_EXT: "${STUDENT_WEB__WEB_SERVER_HOST_EXT}"
                        STUDENT_WEB__WEB_SERVER_HOST_INT: "${STUDENT_WEB__WEB_SERVER_HOST_INT}"
                        STUDENT_WEB__WEB_SERVER_WWW: "${STUDENT_WEB__WEB_SERVER_WWW}"
                        STUDENT_WEB__CSSOW_API_URI: "${STUDENT_WEB__CSSOW_API_URI}"
                        STUDENT_WEB__DEFAULT_INSTITUTE: "${STUDENT_WEB__DEFAULT_INSTITUTE}"
                        STUDENT_WEB__DEFAULT_DEPARTMENT: "${STUDENT_WEB__DEFAULT_DEPARTMENT}"
                        STUDENT_WEB__DEFAULT_SCHEMEOFWORK: "${STUDENT_WEB__DEFAULT_SCHEMEOFWORK}"
                links:
                        - "${TEACHER_WEB__WEB_SERVER_HOST_INT}:${TEACHER_WEB__WEB_SERVER_HOST_EXT}"
                ports:
                        - "${STUDENT_WEB__WEB_SERVER_PORT_INT}:${STUDENT_WEB__WEB_SERVER_PORT_EXT}"
                depends_on:
                        - teacher-web
volumes:
        db_data:
