version: "3.2"
services:
        cssow-db:
                build: ./docker/cssow-db
                image: drussell1974/schemesofwork:cssow-db--1.1.5-mariadb10.5-rc
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: "${CSSOW_DB__ROOT_PASSWORD}"
                        MYSQL_DATABASE: "${CSSOW_DB__DATABASE}"
                        MYSQL_USER: "${CSSOW_DB__USER}"
                        MYSQL_PASSWORD: "${CSSOW_DB__PASSWORD}"
                volumes:
                        - "db_data:${CSSOW_DB__DBSERVER_PATH}"
                        - "db_sqldump:/usr/src/app/sqldump/"
                        - "${CSSOW_DB__BUILD_SCRIPT_PATH_SOURCE}:${CSSOW_DB__BUILD_SCRIPT_PATH_DEST}"
        teacher-web:
                build: ./docker/teacher-web
                image: drussell1974/schemesofwork:teacher-web--1.1.5-python3-rc
                environment:
                        TEACHER_WEB__WEB_SERVER_IP: "${TEACHER_WEB__WEB_SERVER_IP}"
                        TEACHER_WEB__WEB_SERVER_PORT_EXT: "${TEACHER_WEB__WEB_SERVER_PORT_EXT}"
                        TEACHER_WEB__WEB_SERVER_PORT_INT: "${TEACHER_WEB__WEB_SERVER_PORT_INT}"
                        TEACHER_WEB__WEB_SERVER_HOST_EXT: "${TEACHER_WEB__WEB_SERVER_HOST_EXT}"
                        TEACHER_WEB__WEB_SERVER_HOST_INT: "${TEACHER_WEB__WEB_SERVER_HOST_INT}"
                        TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_EXT: "${TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_EXT}"
                        TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_INT: "${TEACHER_WEB__WEB_SERVER_ALLOWED_HOST_INT}"
                        TEACHER_WEB__WEB_SERVER_SECRET_KEY: "${TEACHER_WEB__WEB_SERVER_SECRET_KEY}"
                        TEACHER_WEB__WEB_SERVER_DEBUG: "${TEACHER_WEB__WEB_SERVER_DEBUG}"
                        STUDENT_WEB__WEB_SERVER_WWW: "${STUDENT_WEB__WEB_SERVER_WWW}"
                        EMAIL_SERVER__HOST_EXT: "${EMAIL_SERVER__HOST_EXT}"
                        EMAIL_SERVER__PORT_EXT: "${EMAIL_SERVER__PORT_EXT}"
                        EMAIL_SERVER__HOST_USER: "${EMAIL_SERVER__HOST_USER}"
                        CSSOWMODEL_APP__VERSION: "${CSSOWMODEL_APP__VERSION}"
                        CSSOW_DB__HOST_INT: "${CSSOW_DB__HOST_INT}"
                        CSSOW_DB__PORT_INT: "${CSSOW_DB__PORT_INT}"
                        CSSOW_DB__DATABASE: "${CSSOW_DB__DATABASE}"
                        CSSOW_DB__USER: "${CSSOW_DB__USER}"                        
                        CSSOW_DB__PASSWORD: "${CSSOW_DB__PASSWORD}"
                links:
                        - "${CSSOW_DB__HOST_INT}:${CSSOW_DB__HOST_EXT}"
                ports:
                        - "${TEACHER_WEB__WEB_SERVER_PORT_INT}:${TEACHER_WEB__WEB_SERVER_PORT_EXT}"
                depends_on:
                        - cssow-db
        markdown-service:
                build: ./docker/markdown-service
                image: drussell1974/schemesofwork:markdown-service--1.1.5-node14.3
                environment: 
                        MARKDOWN_SERVICE__PORT_INT: "${MARKDOWN_SERVICE__PORT_INT}"
                links:
                        - "${TEACHER_WEB__WEB_SERVER_HOST_INT}:${TEACHER_WEB__WEB_SERVER_HOST_EXT}"
                ports:
                        - "${MARKDOWN_SERVICE__PORT_INT}:${MARKDOWN_SERVICE__PORT_EXT}"
                depends_on:
                        - teacher-web
        student-web:
                build: ./docker/student-web
                image: drussell1974/schemesofwork:student-web--1.1.5-node14.3
                environment: 
                        STUDENT_WEB__WEB_SERVER_IP: "${STUDENT_WEB__WEB_SERVER_IP}"
                        STUDENT_WEB__WEB_SERVER_PORT_EXT: "${STUDENT_WEB__WEB_SERVER_PORT_EXT}"
                        STUDENT_WEB__WEB_SERVER_PORT_INT: "${STUDENT_WEB__WEB_SERVER_PORT_INT}"
                        STUDENT_WEB__WEB_SERVER_HOST_EXT: "${STUDENT_WEB__WEB_SERVER_HOST_EXT}"
                        STUDENT_WEB__WEB_SERVER_HOST_INT: "${STUDENT_WEB__WEB_SERVER_HOST_INT}"
                        STUDENT_WEB__WEB_SERVER_WWW: "${STUDENT_WEB__WEB_SERVER_WWW}"
                        STUDENT_WEB__CSSOW_API_URI: "${STUDENT_WEB__CSSOW_API_URI}"
                        STUDENT_WEB__MARKDOWN_SERVICE_URI: "${STUDENT_WEB__MARKDOWN_SERVICE_URI}"
                        STUDENT_WEB__DEFAULT_SCHEMEOFWORK: "${STUDENT_WEB__DEFAULT_SCHEMEOFWORK}"
                links:
                        - "${TEACHER_WEB__WEB_SERVER_HOST_INT}:${TEACHER_WEB__WEB_SERVER_HOST_EXT}"
                        - "${MARKDOWN_SERVICE__HOST_INT}:${MARKDOWN_SERVICE__HOST_EXT}"
                ports:
                        - "${STUDENT_WEB__WEB_SERVER_PORT_INT}:${STUDENT_WEB__WEB_SERVER_PORT_EXT}"
                depends_on:
                        - teacher-web
                        - markdown-service
volumes:
        db_data:
        db_sqldump: