INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand what algorithms are, how they are implemented as programs on digital devices, and that programs execute by following precise and unambiguous instructions', 'A', '1');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('create and debug simple programs', 'B', '1');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use logical reasoning to predict the behaviour of simple programs', 'C', '1');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use technology purposefully to create, organise, store, manipulate and retrieve digital content', 'D', '1');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('recognise common uses of information technology beyond school', 'E', '1');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use technology safely and respectfully, keeping personal information private; identify where to go for help and support when they have concerns about content or contact on the internet or other online technologies', 'F', '1');

INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('design, write and debug programs that accomplish specific goals, including controlling or simulating physical systems; solve problems by decomposing them into smaller parts', 'A', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use sequence, selection, and repetition in programs; work with variables and various forms of input and output', 'B', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use logical reasoning to explain how some simple algorithms work and to detect and correct errors in algorithms and programs', 'C', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand computer networks, including the internet; how they can provide multiple services, such as the World Wide Web, and the opportunities they offer for communication and collaboration', 'D', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use search technologies effectively, appreciate how results are selected and ranked, and be discerning in evaluating digital content', 'E', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('select, use and combine a variety of software (including internet services) on a range of digital devices to design and create a range of programs, systems and content that accomplish given goals, including collecting, analysing, evaluating and presenting data and information', 'F', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use technology safely, respectfully and responsibly; recognise acceptable/unacceptable behaviour; identify a range of ways to report concerns about content and contact', 'G', '2');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('design, use and evaluate computational abstractions that model the state and behaviour of real-world problems and physical systems', 'A', '3');

INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand several key algorithms that reflect computational thinking [for example, ones for sorting and searching]; use logical reasoning to compare the utility of alternative algorithms for the same problem', 'B', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('use 2 or more programming languages, at least one of which is textual, to solve a variety of computational problems; make appropriate use of data structures [for example, lists, tables or arrays]; design and develop modular programs that use procedures or functions', 'C', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand simple Boolean logic [for example, AND, OR and NOT] and some of its uses in circuits and programming; understand how numbers can be represented in binary, and be able to carry out simple operations on binary numbers [for example, binary addition, and conversion between binary and decimal]', 'D', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand the hardware and software components that make up computer systems, and how they communicate with one another and with other systems', 'E', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand how instructions are stored and executed within a computer system; understand how data of various types (including text, sounds and pictures) can be represented and manipulated digitally, in the form of binary digits', 'F', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('undertake creative projects that involve selecting, using, and combining multiple applications, preferably across a range of devices, to achieve challenging goals, including collecting and analysing data and meeting the needs of known users', 'G', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('create, reuse, revise and repurpose digital artefacts for a given audience, with attention to trustworthiness, design and usability', 'H', '3');
INSERT INTO `cssow`.`sow_content` (`description`, `letter`, `key_stage_id`) VALUES ('understand a range of ways to use technology safely, respectfully, responsibly and securely, including protecting their online identity and privacy; recognise inappropriate content, contact and conduct, and know how to report concerns', 'I', '3');