# Generated by Django 3.1 on 2020-08-11 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeOfWorkListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            options={
                'permissions': [('publish_contentmodel', 'Can pubish Curriculum Content')],
            },
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='ExamBoardModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='KeyStageModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='KS123PathwayModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='LearningObjectiveModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='SchemeOfWorkModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='SoloTaxonomyModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
            ],
            options={
                'permissions': [('view_whiteboard_lessonmodel', 'Can view whiteboard for this Lesson'), ('view_lessonplan_lessonmodel', 'Can View lesson plan for this Lesson')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models.basemodel',),
        ),
    ]
