# Generated by Django 3.1 on 2020-08-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonModel',
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            options={
                'permissions': [('view_whiteboard_lessonmodel', 'Can view whiteboard for this Lesson'), ('view_lessonplan_lessonmodel', 'Can View lesson plan for this Lesson')],
            },
            bases=('models.basemodel',),
        ),
    ]
