# Generated by Django 3.0.8 on 2021-01-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200811_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.BaseModel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.DeleteModel(
            name='SchemeOfWorkListModel',
        ),
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'permissions': [('view_whiteboard_lessonmodel', 'Can view whiteboard for this Lesson')]},
        ),
    ]
