# Generated by Django 3.1.5 on 2021-05-05 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_departmentmodel_teacherpermissionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='AcademicYearPeriodModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='BaseContextModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='LessonScheduleModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='NotifyModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='PathwayTemplateModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel')),
            ],
            bases=('models.basemodel',),
        ),
        migrations.AlterModelOptions(
            name='teacherpermissionmodel',
            options={'permissions': [('can_manage_team_permissions', 'Can Manage Team Permissions'), ('can_request_team_permissions', 'Can Request Team Permissions')]},
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='schemeofworkmodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='teacherpermissionmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='teacherpermissionmodel',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basemodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DepartmentContextModel',
            fields=[
                ('basecontextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basecontextmodel')),
            ],
            bases=('models.basecontextmodel',),
        ),
        migrations.CreateModel(
            name='InstituteContextModel',
            fields=[
                ('basecontextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basecontextmodel')),
            ],
            bases=('models.basecontextmodel',),
        ),
        migrations.CreateModel(
            name='SchemeOfWorkContextModel',
            fields=[
                ('basecontextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.basecontextmodel')),
            ],
            bases=('models.basecontextmodel',),
        ),
        migrations.CreateModel(
            name='InstituteModel',
            fields=[
                ('institutecontextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.institutecontextmodel')),
            ],
            bases=('models.institutecontextmodel',),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='departmentcontextmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.departmentcontextmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemeofworkmodel',
            name='schemeofworkcontextmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.schemeofworkcontextmodel'),
            preserve_default=False,
        ),
    ]
