
ALTER TABLE sow_content
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_cs_concept
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_department
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_exam_board
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_institute
MODIFY COLUMN created DATETIME ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sow_key_stage
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_key_word
MODIFY COLUMN created DATETIME ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sow_ks123_pathway
MODIFY COLUMN created DATETIME ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sow_learning_objective
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_lesson
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_lesson_plan
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_menu
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_play_based
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_resource
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_resource_type
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_scheme_of_work
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_solo_taxonomy
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_subject_purpose
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_topic
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sow_year
MODIFY COLUMN created DATETIME DEFAULT CURRENT_TIMESTAMP;