version: '3.1'
services:
        db:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD:Admin1.
        adminer:
                image: adminer
                restart: always
                ports: 
                        - 3306:3306
